spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        defualt_batch_fetch_size: 100
#    open-in-view: false
#            system out으로 출력되기 때문에 권장되지 않음
#            show_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true
#        페이지 인덱스 1로 시작 -> 다만 페이저블 개게는 0부터 시작해서 데이터가 맞지 않음

logging:
  level:
    org.hibernate.SQL : debug
#    org.hibernate.type : trace




