#Server
server.port=8090
server.servlet.session.timeout=3600

#JDBC
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=cafe2
spring.datasource.password=1234

#MyBatis
mybatis.config-location=classpath:mybatis/myBatisConfig.xml
mybatis.type-aliases-package=com.mulcam.ai.web.vo

#file size limit
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=10MB

#jsp location
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
