sever:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: study
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        type:
          descriptor:
            sql: trace
        ddl_auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
