--------------------------------------------------------
--  파일이 생성됨 - 금요일-2월-19-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "CAFE"."ORDERS" 
   (	"ORDERNO" NUMBER(*,0), 
	"ORDERDATE" DATE, 
	"ORDERMETHOD" VARCHAR2(10 BYTE), 
	"MEMBERID" VARCHAR2(20 BYTE), 
	"PRODCODE" VARCHAR2(10 BYTE), 
	"QUANTITY" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CAFE.ORDERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAFE"."ORDERS_PK" ON "CAFE"."ORDERS" ("ORDERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ORDERS_ORDERNO_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAFE"."ORDERS_ORDERNO_TRG2" BEFORE
    INSERT ON orders
    FOR EACH ROW
     WHEN (
        new.orderno IS NULL
    ) BEGIN
    :new.orderno := orders_orderno_seq2.nextval;
END;

/
ALTER TRIGGER "CAFE"."ORDERS_ORDERNO_TRG2" ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "CAFE"."ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDERNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAFE"."ORDERS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "CAFE"."ORDERS" MODIFY ("ORDERMETHOD" NOT NULL ENABLE);
  ALTER TABLE "CAFE"."ORDERS" MODIFY ("ORDERDATE" NOT NULL ENABLE);
  ALTER TABLE "CAFE"."ORDERS" MODIFY ("ORDERNO" NOT NULL ENABLE);
